from .edit_language import change_lan
from .yes_no import yes_no
from .product_categories import product_categories
from .product_keyboard import product_keyboard
from .contacts_reg_true import contact_true
from .contacts_reg_false import contact_false
from .about_us import about_us
from .order_size import order_size
from .razrabotan import razrabotan